\doxysection{Exit\+Exception类 参考}
\hypertarget{classExitException}{}\label{classExitException}\index{ExitException@{ExitException}}


退出异常  




{\ttfamily \#include $<$exception.\+hpp$>$}



类 Exit\+Exception 继承关系图\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=184pt]{d3/d3a/classExitException__inherit__graph}
\end{center}
\end{figure}


Exit\+Exception 的协作图\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=184pt]{d9/dcd/classExitException__coll__graph}
\end{center}
\end{figure}
\doxysubsubsection*{Public 成员函数}
\begin{DoxyCompactItemize}
\item 
\Hypertarget{classExitException_a9839c74ca6b1ade5930bc90bc7829e92}\label{classExitException_a9839c74ca6b1ade5930bc90bc7829e92} 
{\bfseries Exit\+Exception} (const std\+::string \&message)
\end{DoxyCompactItemize}


\doxysubsection{详细描述}
退出异常 

定义了退出异常类，继承自std\+::runtime\+\_\+error。并非真正的异常，而是用于程序退出的信号。 

该类的文档由以下文件生成\+:\begin{DoxyCompactItemize}
\item 
include/\mbox{\hyperlink{exception_8hpp}{exception.\+hpp}}\end{DoxyCompactItemize}
